training_data = [
    ("What's the schedule for movies today?", 'movie_showtimes'),
    ('List the current movie showtimes', 'movie_showtimes'),
    ('Show me the movies playing in the evening', 'movie_showtimes'),
    ('I want to watch a film, what are the options?', 'movie_showtimes'),
    ('Tell me about the cinema schedule', 'movie_showtimes'),
    ("What's the last movie of the day?", 'movie_showtimes'),
    ('Can you show me the movie times?', 'movie_showtimes'),
    ("When's the first movie of the day?", 'movie_showtimes'),
    ('I need showtimes for today', 'movie_showtimes'),
    ('Any evening showings?', 'movie_showtimes'),
    ('Tell me about the film screenings', 'movie_showtimes'),
    ("I want to see a movie, what's available?", 'movie_showtimes'),
    ("What's on at the movies?", 'movie_screening'),
    ('Give me information on current movies', 'movie_showtimes'),
    ("What's playing at the cinema?", 'movie_screening'),
    ('Give me information on current movies', 'movie_showtimes'),
    ("What's the movie schedule?", 'movie_showtimes'),
    ('Night showings?', 'movie_showtimes'),
    ('Screening', 'movie_screening'),
    ('Showtimes', 'movie_showtimes'),
    ('Showtime', 'movie_showtimes'),
    ('showing', 'movie_screening'),
    ('played', 'movie_screening'),
    ('playing', 'movie_screening'),
    ('seats available', 'movie_seat_availability'),
    ('sit', 'movie_seat_availability'),
    ('place', 'movie_seat_availability'),
    ('seat', 'movie_seat_availability'),
    ('what seats are available at 0900', 'movie_seat_availability'),
    ('Purchase tickets for the movie ', 'ticket_booking'),
    ('Reserve a seat for me', 'ticket_booking'),
    ('Book tickets', 'ticket_booking'),
    ('Book tickets', 'ticket_booking'),
    ('Buy tickets', 'ticket_booking'),
    ('Purchase tickets', 'ticket_booking'),
    ('Book movie tickets', 'ticket_booking'),
    ('buy movie ticket', 'ticket_booking'),
    ('buy movie tickets', 'ticket_booking'),
    ('buy tickets', 'ticket_booking'),
    ('Cancel my tickets', 'ticket_cancelling'),
    ("I don't want to watch the movie anymore", 'ticket_cancelling'),
    ('View my booking', 'show_bookings'),
    ('Show my booking', 'show_bookings'),
    ('Could you tell me what I booked?', 'show_bookings'),
    ('summary', 'movie_info_summary'),
    ('about?', 'movie_info_summary'),
    ('what is this movie about?', 'movie_info_summary'),
    ('popular', 'movie_info_popularity'),
    ('top 10 movies', 'movie_info_popularity'),
    ('runtime', 'movie_info_runtime'),
    ('how long is the movie', 'movie_info_runtime'),
    ('rating', 'movie_info_rating'),
    ('rated', 'movie_info_classification'),
    ('act', 'movie_info_character'),
    ('acting', 'movie_info_character'),
    ('acted', 'movie_info_character'),
    ('actors', 'movie_info_character'),
    ('starring', 'movie_info_character'),
    ('starred', 'movie_info_character'),
    ('directed', 'movie_info_director'),
    ('director', 'movie_info_director'),
    ('past movies', 'movie_info_past'),
    ('which movies were screening in the past?', 'movie_info_past'),
    ('Call', 'name_mgmt'),
    ('Name', 'name_mgmt'),
    ("Hi, I'm Tan Zhi Xuan", 'name_mgmt'),
    ('change my name', 'change_name'),
    ('Nothing', 'exit'),
    ('Exit', 'exit'),
    ('log0ut', 'exit'),
    ('bye', 'exit'),
    ('logoff', 'exit'),
    ('logout', 'exit'),
    ('go back', 'back'),
    ('step back', 'back'),
    ('register', 'register'),
    ('signup', 'register'),
    ('create an account', 'register'),
    ('login', 'login'),
    ('log in', 'login'),
    ('sign in', 'login'),
    ('comedy movies', 'genre'),
    ('action movies', 'genre'),
    ('genre', 'genre'),
    ('09:00', 'time'),
    ('11:00', 'time'),
    ('1:00', 'time'),
    ('UA rated', 'cert_rating'),
    ('U rated', 'cert_rating'),
    ('R rated', 'cert_rating'),
    ('16 rated', 'cert_rating'),
    ('PG-13 rated', 'cert_rating'),
    ('18+ rated', 'cert_rating'),
    ('A rated', 'cert_rating'),
    ('what can you do?', 'bot_enquiries'),
    ('what are your capabilities?', 'bot_enquiries'),
    ("how's the weather looking like today?", 'bot_enquiries_weather'),
    ('what time is it?', 'bot_enquiries_time'),
    ('how are you feeling?', 'bot_enquiries_sentimental'),
    ('thank you', 'gratitude'),
    ('appreciate it', 'gratitude'),
    ('you are a lifesaver', 'gratitude'),
    ('much obliged', 'gratitude'),
    ('thank you', 'gratitude'),
    ('thank you!', 'gratitude'),
    ('anal', 'swear_words'),
    ('anus', 'swear_words'),
    ('arse', 'swear_words'),
    ('ass', 'swear_words'),
    ('ballsack', 'swear_words'),
    ('bastard', 'swear_words'),
    ('bitch', 'swear_words'),
    ('biatch', 'swear_words'),
    ('bloody', 'swear_words'),
    ('blowjob', 'swear_words'),
    ('blow job', 'swear_words'),
    ('bollock', 'swear_words'),
    ('bollok', 'swear_words'),
    ('boner', 'swear_words'),
    ('boob', 'swear_words'),
    ('bugger', 'swear_words'),
    ('bum', 'swear_words'),
    ('butt', 'swear_words'),
    ('buttplug', 'swear_words'),
    ('clitoris', 'swear_words'),
    ('cock', 'swear_words'),
    ('coon', 'swear_words'),
    ('crap', 'swear_words'),
    ('cunt', 'swear_words'),
    ('damn', 'swear_words'),
    ('dick', 'swear_words'),
    ('dildo', 'swear_words'),
    ('dyke', 'swear_words'),
    ('fag', 'swear_words'),
    ('feck', 'swear_words'),
    ('fellate', 'swear_words'),
    ('fellatio', 'swear_words'),
    ('felching', 'swear_words'),
    ('fuck', 'swear_words'),
    ('f u c k', 'swear_words'),
    ('fudgepacker', 'swear_words'),
    ('fudge packer', 'swear_words'),
    ('flange', 'swear_words'),
    ('Goddamn', 'swear_words'),
    ('God damn', 'swear_words'),
    ('hell', 'swear_words'),
    ('homo', 'swear_words'),
    ('jerk', 'swear_words'),
    ('jizz', 'swear_words'),
    ('knobend', 'swear_words'),
    ('knob end', 'swear_words'),
    ('labia', 'swear_words'),
    ('lmao', 'swear_words'),
    ('lmfao', 'swear_words'),
    ('muff', 'swear_words'),
    ('nigger', 'swear_words'),
    ('nigga', 'swear_words'),
    ('penis', 'swear_words'),
    ('piss', 'swear_words'),
    ('poop', 'swear_words'),
    ('prick', 'swear_words'),
    ('pube', 'swear_words'),
    ('pussy', 'swear_words'),
    ('queer', 'swear_words'),
    ('scrotum', 'swear_words'),
    ('sex', 'swear_words'),
    ('shit', 'swear_words'),
    ('s hit', 'swear_words'),
    ('sh1t', 'swear_words'),
    ('slut', 'swear_words'),
    ('smegma', 'swear_words'),
    ('spunk', 'swear_words'),
    ('tit', 'swear_words'),
    ('tosser', 'swear_words'),
    ('turd', 'swear_words'),
    ('twat', 'swear_words'),
    ('vagina', 'swear_words'),
    ('wank', 'swear_words'),
    ('whore', 'swear_words'),
    ('wtf', 'swear_words'),
    ('go back', 'back'),
    ('what can you do?', 'bot_capabilities'),
    ('what are your capabilities', 'bot_capabilities'),
    ('what state am I currently in?', 'rewind'),
    ('what is the summary of this movie again?', 'movie_info_summary'),
    ('help me', 'help'),
    ('help', 'help'),
    ('what is your name?', 'chatbot_name'),
    ('what is the summary of Deadpool', 'movie_info_summary'),
    ('summmmamamamry of hte movie Deadpool', 'movie_info_summary'),
    ('what is the suummammamamamry of the movie Deadpool', 'movie_info_summary'),
    ('cancel my booking', 'ticket_cancelling'),
    ('what movies are currently screening now?', 'movie_screening'),
    ('what movies are currently playing', 'movie_screening'),
    ('what is the weather today?', 'bot_enquiries_weather'),
    ('what is summmamamamamamry of movie Deadpool', 'movie_info_summary'),
]
